version: "3.8"
services:
  backend:
    image: "mckillem/springboot-react-fullstack:16.12.2022.17.56.57"
    ports:
      - "80:8080"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev