version: "3.8"
services:
  backend:
    image: "mckillem/springboot-react-fullstack:17.12.2022.10.7.27"
    ports:
      - "80:8080"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev